### ISSUE TITLE
About the visualizations of the paper

### ISSUE THREAD

**Issue by MAX-OTW** [MISTLab/vpr-calibration-and-uncertainty#1]
Hello, @lajoiepy,-I really appreciate for your work！Congratulations :)
The visualizations(like  **Fig. 3，Fig. 4，Fig. 5 and Fig. 6**)in the paper look great. Currently I want to try to implement them but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by lajoiepy** [comment]
Hi! Thank you for your interest, the data for evaluation are logged here https://github.com/lajoiepy/vpr-and-uncertainty-calibrator/blob/26125df1fede7d45cc3579b25ff8b3852dd4fdb8/vpr/utils.py . The code for figure generation will not be released for now, since it is entangled with a larger body of code and dependencies, and needs clean up for which I don't have time now. I'll keep this thread updated when I will release it.
